/**
 * Extracts clip metadata from src/data/scenes.js and writes
 * a lightweight copy to api/_lib/scenes-data.js for use by
 * serverless functions (which can't import from src/).
 *
 * Run: node scripts/sync-clips.js
 */

import { writeFileSync } from "node:fs";

const { SCENES } = await import("../src/data/scenes.js");

const clips = SCENES.map((s) => ({
  id: s.id,
  videoId: s.videoId || null,
  type: s.type || "youtube",
  videoUrl: s.videoUrl || null,
  source: s.source?.title || "Unknown",
}));

const output = `// Auto-generated by scripts/sync-clips.js — do not edit manually
// Last synced: ${new Date().toISOString()}
// Total clips: ${clips.length}

export const CLIPS = ${JSON.stringify(clips, null, 2)};
`;

writeFileSync("api/_lib/scenes-data.js", output);
console.log(`Synced ${clips.length} clips to api/_lib/scenes-data.js`);
