import { normalizeProgram } from './tsl-normalize.mjs';
import Linker from 'three/addons/transpiler/Linker.js';
import TSLEncoder from 'three/addons/transpiler/TSLEncoder.js';
import { programs } from './tsl-programs.mjs';

class ScopedLinker extends Linker {
  evalProperty(node) {
    // Member writes count as writes to the base value, including function
    // parameters, which GLSL passes by value unless explicitly qualified.
    if (node.isAccessorElements) return this.evalProperty(node.object);
    if (node.isOperator && node.type === '.') return this.evalProperty(node.left);
    return super.evalProperty(node).split('.')[0];
  }
}

class FactoryEncoder extends TSLEncoder {
  emit(ast) {
    this.inlineFunctions = new Map(ast.body.filter(node => node.isFunctionDeclaration && node.layout === false).map(node => [node.name, node.type]));
    return super.emit(ast);
  }
  emitExpression(node) {
    const code = super.emitExpression(node);
    // Inline Fn() is lazy. A call used as a GLSL statement must enter the stack
    // even when its result is unused (particleFallback writes the shared output).
    return node.isFunctionCall && this.inlineFunctions.has(node.name) && this.inlineFunctions.get(node.name) !== 'void' && node.parent?.body?.includes(node) ? code + '.toVar().toStack()' : code;
  }
  emitFunction(node) {
    const code = super.emitFunction(node).replace(/^export /, '');
    // The string form declares the return type without a fixed layout. In r186
    // only explicit void Fn calls enqueue the underlying call automatically;
    // .toStack() on an untyped call instead queues a discarded VarIntent wrapper.
    return node.layout === false ? code.replace(/} \);\n$/, `}, '${node.type}' );\n`) : code;
  }
  emitVariables(node, isRoot = true) {
    // GLSL locals own storage even when initialized from a uniform or varying.
    // r186's assignment analysis misses member writes; comma chains also attach
    // .toVar() to the final initializer. Emit each declarator independently.
    const next = node.next;
    node.next = null;
    if (!node.immutable) node.needsToVar = node.value !== null;
    const code = super.emitVariables(node, isRoot);
    node.next = next;
    return code + (next ? ', ' + this.emitVariables(next, false) : '');
  }
}

export function generateModule(definitions = programs) {
  const imports = new Set(), factories = [], names = new Set();
  for (const program of definitions) {
    if (names.has(program.name)) throw new Error(`Duplicate factory ${program.name}`);
    names.add(program.name);
    const { ast, inputs, output, exports: functions } = normalizeProgram(program);
    new ScopedLinker().process(ast);
    const encoder = new FactoryEncoder();
    const emitted = encoder.emit(ast);
    for (const key of encoder.imports) imports.add(key);
    if (output) imports.add('property');
    // The emitter owns all expression code; only its ESM header is assembled here.
    const body = emitted.replace(/^\/\/ Three\.js Transpiler r186\n\n/, '').replace(/^import .*?;\n/, '')
      .replace(/\t/g, '  ').split('\n').map(line => line.trimEnd()).join('\n').trim();
    const parameters = inputs.size ? '{ ' + [...inputs].map(([key, alias]) => `${key}: ${alias}`).join(', ') + ' }' : '';
    factories.push(`export function ${program.name}(${parameters}) {\n${output ? "  const shaderOutput = property('vec4');\n" : ''}${body.split('\n').map(line => line ? '  ' + line : '').join('\n')}\n\n  return { ${functions.map(([key, value]) => `${key}: ${value}`).join(', ')} };\n}`);
  }
  return `// Generated by tools/tsl-generate.mjs with Three.js r186. Do not edit.\n// Sources: tools/tsl-captured-programs.json and tools/tsl-programs.mjs.\nimport { ${[...imports].sort().join(', ')} } from 'three/tsl';\n\n${factories.join('\n\n')}\n`;
}
