import { put } from "@vercel/blob";
import { CLIPS } from "./_lib/scenes-data.js";
import { checkAllClips } from "./_lib/check-video.js";

const BLOB_KEY = "sweep-report.json";

async function updateEdgeConfigBlocklist(deadIds) {
  const edgeConfigId = process.env.EDGE_CONFIG?.match(/ecfg_[a-z0-9]+/)?.[0];
  const token = process.env.VERCEL_API_TOKEN;
  if (!edgeConfigId || !token) return;

  const url = new URL(`https://api.vercel.com/v1/edge-config/${edgeConfigId}/items`);
  if (process.env.VERCEL_TEAM_ID) {
    url.searchParams.set("teamId", process.env.VERCEL_TEAM_ID);
  }

  try {
    await fetch(url, {
      method: "PATCH",
      headers: {
        Authorization: `Bearer ${token}`,
        "Content-Type": "application/json",
      },
      body: JSON.stringify({
        items: [{ operation: "upsert", key: "deadClips", value: deadIds }],
      }),
    });
  } catch {
    // Non-critical — blob report is the primary output
  }
}

async function createGitHubIssue(dead) {
  const token = process.env.GITHUB_TOKEN;
  if (!token) return;

  const date = new Date().toISOString().slice(0, 10);
  const rows = dead
    .map((c) => `| ${c.id} | ${c.videoId || c.videoUrl || "—"} | ${c.type} | ${c.source} |`)
    .join("\n");

  const body = `## Dead Links Report — ${date}

| Clip ID | Video ID / URL | Type | Source |
|---------|----------------|------|--------|
${rows}

_Auto-generated by \`/api/sweep\` cron job._`;

  try {
    await fetch("https://api.github.com/repos/BurntFrost/so-i-started-blasting/issues", {
      method: "POST",
      headers: {
        Authorization: `Bearer ${token}`,
        Accept: "application/vnd.github+json",
        "X-GitHub-Api-Version": "2022-11-28",
      },
      body: JSON.stringify({
        title: `🔗 Dead links found: ${dead.length} clips (${date})`,
        body,
        labels: ["dead-links"],
      }),
    });
  } catch {
    // Fire-and-forget — blob report is the primary output
  }
}

export default async function handler(req, res) {
  // Verify cron secret
  const auth = req.headers.authorization;
  if (auth !== `Bearer ${process.env.CRON_SECRET}`) {
    return res.status(401).json({ error: "Unauthorized" });
  }

  try {
    const { healthy, dead, unknown } = await checkAllClips(CLIPS);

    const report = {
      timestamp: new Date().toISOString(),
      total: CLIPS.length,
      healthyCount: healthy.length,
      deadCount: dead.length,
      unknownCount: unknown.length,
      dead: dead.map((c) => ({
        id: c.id,
        videoId: c.videoId,
        type: c.type,
        source: c.source,
      })),
      unknown: unknown.map((c) => ({
        id: c.id,
        videoId: c.videoId,
        type: c.type,
        source: c.source,
      })),
    };

    await put(BLOB_KEY, JSON.stringify(report), {
      access: "public",
      addRandomSuffix: false,
      contentType: "application/json",
    });

    // Write dead clip IDs to Edge Config so the frontend auto-hides them
    const deadIds = dead.map((c) => c.id);
    await updateEdgeConfigBlocklist(deadIds);

    if (dead.length > 0) {
      await createGitHubIssue(dead);
    }

    return res.status(200).json({
      message: `Sweep complete: ${dead.length} dead, ${unknown.length} unknown, ${healthy.length} healthy`,
    });
  } catch (err) {
    return res.status(500).json({ error: err.message });
  }
}
